import localFont from 'next/font/local'
import './globals.css'

const mainFont = localFont({ src: '../BlenderPro-Medium.woff2' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mainFont.className}><div className="bg-secondary min-h-screen text-white">
        {children}
      </div></body>
    </html>
  )
}
